### ISSUE TITLE
Line frequency from pyde1.conf not being applied on start

### ISSUE THREAD

**Issue by a112358132134** [jeffsf/pyDE1#20]
Relates to pyde1 v1.0.0.

`journalctl` shows that pyde1 successfully loads the config file on startup:
```
Jan 14 07:51:24 de1server pyde1[3243]: 2022-01-14 07:51:24,888 INFO [MainProcess] Config.YAML: Loading config overrides from /usr/local/etc/pyde1/pyde1.conf
Jan 14 07:51:25 de1server pyde1[3243]: 2022-01-14 07:51:25,019 INFO [MainProcess] Config.YAML: Config overrides loaded from /usr/local/etc/pyde1/pyde1.conf
```
And the config file `/usr/local/etc/pyde1/pyde1.conf` includes:
```
de1:
    LINE_FREQUENCY 50 # Hz
```

Yet after startup and connecting to the DE1, `curl http://<ip:port>/de1/calibration/line_frequency` returns the following each time
```
{
    "hz": 60
}
```

1. If the Hz value in the config file should always be applied to every DE1 on connection, then this doesn't appear to be occurring.
2. If the config file is just the default for a new DE1, and the per-device value is saved elsewhere, then this isn't saving or loading correctly between restarts.

NB: The `flow_calibration` value does stay between restarts.

Is there any other information you would need to reperform or understand the situation?

--------------
pyde1 info:
 * version: 1.0.0
 * installed: from git, using modified scripts based on the template ones

DE1 info:
 * v1.0 (no GHC)

General system info:
'''
[manjaro@de1server ~]$ neofetch 
██████████████████  ████████   manjaro@de1server 
██████████████████  ████████   ----------------- 
██████████████████  ████████   OS: Manjaro ARM Linux aarch64 
██████████████████  ████████   Host: Pine64 PinePhone (1.2) 
████████            ████████   Kernel: 5.15.11-1-MANJARO-ARM 
████████  ████████  ████████   Uptime: 8 mins 
████████  ████████  ████████   Packages: 814 (pacman) 
████████  ████████  ████████   Shell: bash 5.1.12 
████████  ████████  ████████   Resolution: 720x1440 
████████  ████████  ████████   Terminal: /dev/pts/0 
████████  ████████  ████████   CPU: (4) @ 1.152GHz 
████████  ████████  ████████   Memory: 693MiB / 1991MiB 
████████  ████████  ████████
████████  ████████  ████████                           
                                                       
'''

**Comment by jeffsf** [comment]
There is no internal storage or estimation of the line frequency in the DE1 hardware. It is solely a software value. Its primary, if not only use is to estimate dispensed volume. The DE1 typically reports every 25 half-cycles, so the time for the summation is different for 50 and 60 Hz mains.

Confirmed that the DE1 singleton is being initialized with the default value of 60, rather than that from the loading of the config file.
