### ISSUE TITLE
Use of deprecated Callable definition

### ISSUE THREAD

**Issue by a112358132134** [jeffsf/pyDE1#27]
When running the release version `1.1.0` of pyde1 against python 3.10, pyde1 crashes shortly after startup.  The root cause appears to be use of a deprecated importation definition of `Callable`.

With the following edit to line 51 of `src/pyDE1/api/outbound/mqtt/run.py` this error disappears:
```
# OLD line 51
from collections import Callable
# NEW line 51
from collections.abc import Callable
```

Relevant documentation highlighting this was deprecated in python 3.3, and removed in 3.10:
[https://docs.python.org/3.9/library/collections.html](https://docs.python.org/3.9/library/collections.html)
```
Deprecated since version 3.3, will be removed in version 3.10: Moved [Collections Abstract Base Classes](https://docs.python.org/3.9/library/collections.abc.html#collections-abstract-base-classes) to the [collections.abc](https://docs.python.org/3.9/library/collections.abc.html#module-collections.abc) module. For backwards compatibility, they continue to be visible in this module through Python 3.9.
```

**Comment by jeffsf** [comment]
Thanks!

I didn't find any other "inappropriate" uses of `collections` as `collections.deque` still appears [there in Python 3.10](https://docs.python.org/3.10/library/collections.html)

If I missed one, please let me know.

**Comment by a112358132134** [comment]
Looks like none of the actual containers moved to `.abc`, just the base classes that underpin/support them.

No other issues have come up for me using 3.10 apart from the one noted above. 

Thanks for resolving.
